### ISSUE TITLE
Requesting paginated search results

### ISSUE THREAD

**Issue by mprasanjith** [tjrgg/simple-youtube-api#12]
As of now there doesn't seem to be a way to load the next set of results for a search because the YouTube `nextPageToken` isn't returned with the search results. Is this planned in a future release? For performance reasons I don't want to load hundreds of results at once.

**Comment by appellation** [comment]
The search method should automatically paginate results.

**Comment by mprasanjith** [comment]
I already saw that the search method can return more than 50 results at once with multiple requests to YouTube API. But I'm not interested in loading all the results at once. What I'm looking for is a way to load let's say 50 results at once, and then load the next 50 at a later point.

**Comment by Delivator** [comment]
Is this still now working?
