### ISSUE TITLE
Missing some stuff

### ISSUE THREAD

**Issue by iamaul** [tjrgg/simple-youtube-api#19]
It's weird that channel title is undefined when I'm trying to catch from an array, it is big difference with `searchVideos` which fetched all stuff. I log the channels and there's no title object. It seems kind of missing some stuff in `searchChannels`. I got these problems just now in the latest version

channel search method:
```
yts.searchChannels(args.join(" "), 10).then(channels => {
msg.channel.send(new Discord.MessageEmbed().setColor(0x00AE86).setTitle("Select Channels").setDescription(Object.keys(channels).map((x, i) => `[${i + 1}] ${channels[x].title}`).join("\n")).setFooter("Select channels from [1-10] or 'cancel' to cancel selection.")).then(mesg => {
```

channel search results:
https://imgur.com/a/SjA3y

log channels:
https://pastebin.com/9KqDDnjt

video search results:
https://imgur.com/a/WptHM

log videos:
https://pastebin.com/5uhaCQfV

**Comment by appellation** [comment]
Is there any possibility you could show what the `raw.snippet` contains?

**Comment by iamaul** [comment]
Fixed, thanks for replying. It was `channels[x].raw.snippet.title`. just realised now that `raw.snippet` contains the object 👍 https://imgur.com/a/GTfon

**Comment by appellation** [comment]
I'm concerned that this isn't getting properly applied to the channel object, however.  I'll take a closer look when I get the chance.
