### ISSUE TITLE
durationSeconds returning -1

### ISSUE THREAD

**Issue by Jayden000** [tjrgg/simple-youtube-api#32]
When attempting to use video[0].durationSeconds it always returns -1. For every video I do it on. I use a different API and it returns the correct duration. I need this API to return the duration as I need to bundle it all up into one object/array because I am not sure how to add a property onto an object.

**Comment by appellation** [comment]
Are you requesting the `contentDetails` snippet?

**Comment by Jayden000** [comment]
contentDetails?

**Comment by Jayden000** [comment]
contentDetails?

**Comment by Jayden000** [comment]
?

**Comment by BudimirDjordjevic** [comment]
I'm getting the same issue. Can you please fix this?

**Comment by jvlobo** [comment]
Hi guys. I've also run into this issue. I've been reading a bit of [Youtube's API documentation](https://developers.google.com/youtube/v3/docs/playlistItems), and found this:

<img width="1097" alt="screenshot 2019-01-08 at 06 10 09" src="https://user-images.githubusercontent.com/5671420/50790982-2a328500-130c-11e9-9a11-39ee3f25beb0.png">

So I don't see a way to get the video duration for each item in the playlist... 😕
Is the only solution to make individual calls for each video in the playlist?
What are your thoughts on this @appellation ??

**Comment by Jayden000** [comment]
> 
> 
> I fix this fetching the video before use them. using the option { part : contentDetails }, see video.fetch()

Example?

**Comment by jvlobo** [comment]
My way to go around this issue has been to retrieve every video individually... that's the only way I've been able to get all the information for the videos in a playlist, something like:

```
import YouTube from 'simple-youtube-api';
import { youtubeApiKey } from '../../config/config';
const youtube = new YouTube(youtubeApiKey);

const getYoutubePlaylistVideos = async (url) => {
  try {
    const playlist = await youtube.getPlaylist(url);
    const videos = await playlist.getVideos(100, { part: 'snippet' });
    const videoPromises = [];

    for (const v of videos)
      v.title !== 'Private video' && v.thumbnails
        && videoPromises.push(youtube.getVideoByID(v.id));

    const youtubeVideos = await Promise.all(videoPromises)

    return youtubeVideos;
  } catch(err) {
    throw new Error(err.message)
  }
};
```

I hope it helps :)

**Comment by D4RKAR117** [comment]
It's strange, at least in my case it was the search video method, or the search playlist method, the videos that are always returned returned only with basic information, after the fetch the properties of the options are added like the part, and the durations work

**Comment by appellation** [comment]
This is due to a limitation of the YouTube API and there isn't much we can do about it short of providing some sort of "auto-fetch" functionality when searching (something I wouldn't be very excited for, since it's extra API calls, extra time, and pretty easy to implement manually if you need the data). The reason this issue is still open is because the OP hasn't clarified how he's fetching the videos; if the full data is being fetched with the [`contentDetails`](https://github.com/HyperCoder2975/simple-youtube-api/issues/32#issuecomment-430310287) part and the duration is still -1, this would be a bug.

**Comment by D4RKAR117** [comment]
What I was referring to is that by default, even requesting with the options of contentDetails, durationsSeconds and other properties referring to these options do not work, they only work until a fetch() of the video is made that the search methods return. So if that's what you mean by the limitation of the YouTube API and that it is the normal procedure that should always be executed, then it should be specified in the package documentation, which in addition to the search options should be done a fetch() to the video to work correctly and thus avoid future misunderstandings. :D
