### ISSUE TITLE
Error: No playlist ID found in URL

### ISSUE THREAD

**Issue by PitchRE** [tjrgg/simple-youtube-api#52]
**getPlaylist()** doesn't know how to parse playlist with url schema like this [https://youtu.be/0rtV5esQT6I?list=PLzm9sEXjZ90feWaeV0XuOuRaQqLTHVKDv](url)

`Error: No playlist ID found in URL: https://youtu.be/OcnrboRX0lQ?list=PLsifFPg4DahLSyJGdibUXNKC8_tn1v0_d`

version:     "simple-youtube-api": "^5.2.1",

**Comment by tjrgg** [comment]
I'm working on finishing up the next major version (6.0.0) and I will incorporate a fix for this in that version. I should have it released soon.

**Comment by PitchRE** [comment]
Thanks for fast response. Looking forward for it.
