### ISSUE TITLE
DurationSeconds returning -1 for all videos

### ISSUE THREAD

**Issue by skyla-skye** [tjrgg/simple-youtube-api#54]
The following code always returns `undefined` for duration and `-1` for durationSeconds no matter what video im searching for and it also happens with `youtube.getPlaylist(...).getVideos()`
although `youtube.getVideo()` returns the correct duration and durationSeconds
`youtube.searchVideos('coffin dance meme', 1).then(v => console.log(v[0].title, v[0].duration, v[0].durationSeconds, v[0].url))`

**Comment by tjrgg** [comment]
This is normal behavior. To get the duration, you need to fetch the full video using `Video.fetch()` (or the `youtube.getVideo()` method you referenced). That'll get the duration for you.
