### ISSUE TITLE
Could not find a declaration file for module

### ISSUE THREAD

**Issue by laxadev** [tjrgg/simple-youtube-api#55]
When I try to use it in AdonisJS I get this message:

_Could not find a declaration file for module 'simple-youtube-api'. '.../node_modules/simple-youtube-api/src/index.js' implicitly has an 'any' type.
  Try `npm install @types/simple-youtube-api` if it exists or add a new declaration (.d.ts) file containing `declare module 'simple-youtube-api';`_

I'm loading the package like:
`const YouTube = require("simple-youtube-api");`

**Comment by tjrgg** [comment]
v5 of `simple-youtube-api` does not include types. If you want to use v5 with TypeScript, you'd have to create your own declaration file.

Alternatively, you can wait for [v6](https://github.com/tjrgg/simple-youtube-api/tree/next), which is currently in development and written in TypeScript.
