### ISSUE TITLE
Getting related videos for ID

### ISSUE THREAD

**Issue by Q-u-y** [tjrgg/simple-youtube-api#57]
Hi. A quick question. Is it possible to retrieve a list of videos related to a certain video? I tried using search with `relatedToVideoId` as an option but it's not working. Not sure if it's possible or I'm using the option incorrectly. Thanks.

**Comment by tjrgg** [comment]
What's the code you are using and what are the resulting errors, if any?

**Comment by Q-u-y** [comment]
I was testing with `.search("list", 4,  { relatedToVideoId: "videoID" })` but after going over the source code, it seems the first parameter is the query and not a type. I tried again with `.searchVideos("", 4, { relatedToVideoId: "videoID" })` and it seems to work. So I guess type has to be video and the query is ignored? Can you confirm if this is the right way to do it?

Basically I want to call this from the module:
`https://www.googleapis.com/youtube/v3/search?part=snippet&relatedToVideoId=videoID&type=video&key={API_KEY}`

Thanks.

**Comment by tjrgg** [comment]
Yes, the type does have to be `video` and the way you are doing it looks like the best way to do what you want with the current release.

Perhaps in the next release, we could add a method to `Video` for fetching related videos to clean make that a bit simpler.

**Comment by tjrgg** [comment]
I'll be implementing a `fetchRelated` method in the Video class in the next major release to allow related videos to be fetched and cached.

**Comment by Q-u-y** [comment]
Awesome. Looking forward to it.
