### ISSUE TITLE
getPlaylist doesn't fetch videos

### ISSUE THREAD

**Issue by elliopitas** [tjrgg/simple-youtube-api#60]
it grabs all the video info but the videos array is always empty

**Comment by tjrgg** [comment]
Could you show the code you're using and the error you're getting?

**Comment by elliopitas** [comment]
> Could you show the code you're using and the error you're getting?

```
let playlistinfo=await youtube.getPlaylist(args[0]); \\args[0]=https://www.youtube.com/playlist?list=PLruqoIF23LV910443_s_j9tygFEotfukE
console.log(playlistinfo);
```
console output
Playlist {
  type: 'playlist',
  videos: [],
  raw: {
    kind: 'youtube#playlist',
    etag: '-37CoAeiTrtvgB2Jgm98uEd3WWk',
    id: 'PLruqoIF23LV910443_s_j9tygFEotfukE',
    snippet: {
      publishedAt: '2020-03-29T00:04:50Z',
      channelId: 'UCUpkp-6fXuG9dqfoJ99XTmw',
      title: 'Curse of Strahd RPG Replays',
      description: '',
      thumbnails: [Object],
      channelTitle: 'Puffin Forest',
      localized: [Object]
    }
  },
  channel: Channel {
    type: 'channel',
    raw: {
      kind: 'youtube#playlist',
      etag: '-37CoAeiTrtvgB2Jgm98uEd3WWk',
      id: 'PLruqoIF23LV910443_s_j9tygFEotfukE',
      snippet: [Object]
    },
    full: false,
    kind: 'youtube#playlist',
    id: 'UCUpkp-6fXuG9dqfoJ99XTmw',
    title: 'Puffin Forest'
  },
  id: 'PLruqoIF23LV910443_s_j9tygFEotfukE',
  title: 'Curse of Strahd RPG Replays',
  description: '',
  publishedAt: 2020-03-29T00:04:50.000Z,
  thumbnails: {
    default: {
      url: 'https://i.ytimg.com/vi/VEIf8aRMnXo/default.jpg',
      width: 120,
      height: 90
    },
    medium: {
      url: 'https://i.ytimg.com/vi/VEIf8aRMnXo/mqdefault.jpg',
      width: 320,
      height: 180
    },
    high: {
      url: 'https://i.ytimg.com/vi/VEIf8aRMnXo/hqdefault.jpg',
      width: 480,
      height: 360
    },
    standard: {
      url: 'https://i.ytimg.com/vi/VEIf8aRMnXo/sddefault.jpg',
      width: 640,
      height: 480
    },
    maxres: {
      url: 'https://i.ytimg.com/vi/VEIf8aRMnXo/maxresdefault.jpg',
      width: 1280,
      height: 720
    }
  },
  channelTitle: 'Puffin Forest',
  defaultLanguage: undefined,
  localized: { title: 'Curse of Strahd RPG Replays', description: '' }
}
here's a screenshot too
![image](https://user-images.githubusercontent.com/18124559/86893292-1129b080-c10a-11ea-9bb5-83d6be77086b.png)

btw your wrapper has been very helpful 😃

**Comment by tjrgg** [comment]
Try fetching the videos with `await playlist.fetchVideos()`.

**Comment by elliopitas** [comment]
> Try fetching the videos with `await playlist.fetchVideos()`.

I will try that when I get home Monday and update you
Btw your documentation link is broken

**Comment by tjrgg** [comment]
> Btw your documentation link is broken
There's an updated link in the README.

**Comment by elliopitas** [comment]
thanks you now everything works just fine
